### ISSUE TITLE
Fails to make

### ISSUE THREAD

**Issue by blueish4** [Wattos/logitech-g710-linux-driver#12]
After running `make`, make returns with the following output:

```
for dir in src/kernel src/userspace; do make -C $dir default; done
make[1]: Entering directory `/home/michael/logitech-g710-linux-driver/src/kernel'
make -C /lib/modules/3.15.10-200.fc20.x86_64/build M=/home/michael/logitech-g710-linux-driver/src/kernel modules
make: Entering an unknown directory
make: *** /lib/modules/3.15.10-200.fc20.x86_64/build: No such file or directory.  Stop.
make: Leaving an unknown directory
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/michael/logitech-g710-linux-driver/src/kernel'
make[1]: Entering directory `/home/michael/logitech-g710-linux-driver/src/userspace'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/home/michael/logitech-g710-linux-driver/src/userspace'
```

the folder is in /home/michael. Ideas for fixing?

**Comment by wxl** [comment]
the issue is /lib/modules/3.15.10-200.fc20.x86_64/build. look around and
see if there's something similar in a different directory in /lib/modules
(e.g. `/lib/modules/$(uname -r)`). i hate hardcoding.

**Comment by blueish4** [comment]
/lib/modules/3.15.10-200.fc20.x86_64/build was a symlink to a directory that didn't exist (/usr/src/kernels/3.15.10-200.fc20.x86_64), whereas /usr/src/kernels/3.15.10-200.fc20.x86_64+debug existed. Works now, please mark as resolved.

**Comment by wxl** [comment]
there ya go. hardcoding is the devil.
