### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by redditCommand** [Wattos/logitech-g710-linux-driver#13]
So I followed the directions, and I'm not entirely sure whether or not it worked...my keyboard (I think) is working exactly the same as before. There were error messages, but I'm not sure If I'd call a keyboard that still technically works a failed install. If it did work, I'd expect the m keys to light up as they do with windows, but I'm not sure. How do I check?
Here's the terminal commands and outputs:
https://gist.github.com/redditCommand/b25ea3c938a12891188d

**Comment by blueish4** [comment]
run `xev` and see if pressing the '1' key generates a different output that pressing the 'G1@ key.
