### ISSUE TITLE
Arch Linux (AUR) package

### ISSUE THREAD

**Issue by forivall** [Wattos/logitech-g710-linux-driver#2]
Like you and K900, I am lacking a better way to contact you, so here's an issue.

I would like to convert it to make it use dkms, but it works, and having a package provides a nicer way to uninstall it. (although after going through the process, it's only one file that needs to be removed anyways). Unfortunately, making packages for other distros takes a bit more effort, and I won't be of any help there.

https://github.com/forivall/aur-packages/tree/master/logitech-g710-kmod
https://aur.archlinux.org/packages/logitech-g710-kmod-git/

**Comment by Wattos** [comment]
Apologies for the late response

I find it great that you took the effort to the Arch package. Is there any action required on my part?
