### ISSUE TITLE
Ubuntu 15.10, G* keys are not separated keys

### ISSUE THREAD

**Issue by migmolrod** [Wattos/logitech-g710-linux-driver#24]
I've followed every step in the README.md, yet the G# keys are not separated keys. Instead they're binded to numbers 1 to 6 (not even F1 to F6, which was supposed to be the kind of 'default' keys, according to what I've read from other people).

Following link to link to link to link, I've read so many things that I don't even know what to do.
Example: I've read that newer versions of Ubuntu don't use xmodmap, but xkb. If that's true, how can I rebind those G# keys to make the separated keys so I can then use xbindkeys-config to configure my own commands and so?

Another thing: when I've built from source other applications, I could see literally hundreds of output lines when it's `make install`ing it. This time, output is little to inexistent so I don't even know if the driver is correctly compiled or installed, let alone if it's working. Any way to ensure it?

**Comment by wdouglass** [comment]
It's not. you need to make sure to bind the driver, the kernel won't do it for you. try putting the 90-logitech-g710-plus.rules file from the misc directory in /etc/udev/rules.d and rebooting.
